metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts:
   - "elasticsearch:9200"

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts:
      - "elasticsearch:9200"
  - module: golang
    metricsets:
      - expvar
      - heap
    period: 10s
    hosts:
      - "192.168.0.182:8080"
    heap.path: "/debug/vars"
    expvar:
      namespace: "example"
      path: "/debug/vars"
  - module: kibana
    metricsets: [ "status" ]
    period: 10s
    hosts:
      - "kibana:5601"
    basepath: ""
    enabled: true
